apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-cluster
  region: ap-south-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-1
  spot: true
  ssh:
    publicKeyName: tarun-mu


#To create cluster with above config file.
#eksctl create cluster --config-file=[file-name].yaml
#NOTE: Don't forget to delete the cluster.
#eksctl delete cluster --config-file=[file-name].yaml



---
#https://eksctl.io/usage/creating-and-managing-clusters/

# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: basic-cluster
#   region: eu-north-1

# nodeGroups:
#   - name: ng-1
#     instanceType: m5.large
#     desiredCapacity: 10
#     volumeSize: 80
#     ssh:
#       allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
#   - name: ng-2
#     instanceType: m5.xlarge
#     desiredCapacity: 2
#     volumeSize: 100
#     ssh:
#       publicKeyPath: ~/.ssh/ec2_id_rsa.pub
