apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spot-cluster
  region: ap-south-1

managedNodeGroups:

# `instanceTypes` defaults to [`m5.large`]
- name: spot-1
  instanceType: t2.small
  spot: true
  ssh:
    publicKeyName: ajith-mumbai


#To create cluster with above config file.
#eksctl create cluster --config-file=[file-name].yaml
#NOTE: Don't forget to delete the cluster.
#eksctl delete cluster --config-file=[file-name].yaml



# ---
#https://eksctl.io/usage/creating-and-managing-clusters/

# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: basic-cluster
#   region: ap-south-1

# nodeGroups:
#   - name: ng-1
#     instanceType: t2.small
#     spot: "true"
#     desiredCapacity: 10
#     volumeSize: 30
#     ssh:
#       allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
#       publicKeyName: ajith-mumbai
  # - name: ng-2
  #   instanceType: m5.xlarge
  #   desiredCapacity: 2
  #   volumeSize: 100
  #   ssh:
      # publicKeyPath: ajith-mumbai


# ---

# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: nodes
#   region: ap-south-1

# managedNodeGroups:
#   # `instanceTypes` defaults to [`t2.small`]
#   - name: node-1
#     spot: true
#     ssh:
#       publicKeyName: ajith-mumbai

# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: my-eks-cluster
#   region: ap-south-1

# managedNodeGroups:
#   - name: my-eks-node-group
#     instanceType: t3.small
#     desiredCapacity: 3
#     maxSize: 2
#     minSize: 1
#     spot: true
#     # labels:
#     #   nodegroup-type: worker
#     # tags:
#     #   nodegroup-type: worker
#     ssh:
#       allow: true
#       publicKeyName: ajith-mumbai
